### ISSUE TITLE
Trouble installing iruby in Windows

### ISSUE THREAD

**Issue by robrenard** [SciRuby/iruby#41] opened 2015-07-20 18:06 UTC
I could not install iRuby gem. The problem seems to be occurring during in the installation of the rbczmq 1.7 dependency.

Here is the gem make.out message logged on the C:\Ruby22-x64\lib\ruby\gems\2.2.0\extensions\x64-mingw32\2.2.0\rbczmq-1.7.9.

The message content follows:

C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20150720-6208-162dmho.rb extconf.rb
checking for windows.h... yes
checking for winsock.h... yes
checking for main() in -lkernel32... yes
checking for main() in -lrpcrt4... yes
checking for main() in -lgdi32... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/Ruby22-x64/bin/$(RUBY_BASE_NAME)
	--with-kernel32lib
	--without-kernel32lib
	--with-rpcrt4lib
	--without-rpcrt4lib
	--with-gdi32lib
	--without-gdi32lib
extconf.rb:49:in `<main>': uninitialized constant GNU_CHAIN (NameError)

extconf failed, exit code 1

**Comment by minad** [comment] 2015-07-21 12:48
duplicate of #28

**Closed by minad** 2015-07-21 12:48 UTC

**Comment by domitry** [comment] 2015-11-19 09:29
Yes, but maybe you maybe still fail to install rbczmq on Windows. #50 will solve that.
