### ISSUE TITLE
add a 'Welcome to Ruby' notebook to try.jupyter.org?

### ISSUE THREAD

**Issue by tanyaschlusser** [SciRuby/iruby#44] opened 2015-08-04 17:34 UTC
Hi! I know this would be better on the actual [jupyter repo](https://github.com/jupyter/docker-demo-images) but wanted to ping you here since this is more active for Rubyists. [try.jupyter.org](https://try.jupyter.org/) already has a Ruby kernel built in so all that the repo needs is a ruby notebook with a quick few cells of welcome content.

here's their repo: https://github.com/jupyter/docker-demo-images

I could do it but am a ruby novice. Better someone who can showcase why it would be nice to have ruby on a notebook, right?

**Comment by kojix2** [comment] 2019-02-16 07:45
Current status.

@jimmynguyc create [Welcome to Ruby notebook](https://github.com/jupyter/docker-demo-images/blob/master/notebooks/Welcome%20to%20Ruby.ipynb)  on 21 Oct 2017
[Carreau](/Carreau) merged commit on 24 Oct 2017

But [Docker Demo Image repository](https://github.com/jupyter/docker-demo-images) has been archived.
> This repository has been archived by the owner. It is now read-only. 
> This repo is archived and no longer used. If you would like to include a demo of your Jupyter kernel, please add a link to your own demo to the try jupyter page by adding a link, description, and logo [here](https://github.com/jupyter/jupyter.github.io/blob/master/_data/try.yml). 

We may need to add a link.

**Comment by kojix2** [comment] 2019-02-16 09:27
https://github.com/SciRuby/iruby/issues/126

**Comment by mrkn** [comment] 2019-02-19 07:49
@kojix2 I gave you a permission to close an issue.  Please close duplicated issues.

**Comment by kojix2** [comment] 2019-02-19 08:07
duplicated by #126

**Comment by kojix2** [comment] 2019-02-19 08:18
Duplicate of #126

**Closed by kojix2** 2019-02-19 08:18 UTC
